version: '3'
services:
  author_db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./my_volume:/var/lib/mysql
